{"name": "Incorrect password-user not found", "status": "failed", "statusDetails": {"message": "AssertionError: User not found\nassert 'http://195.133.27.184/login/' == 'http://195.133.27.184/list/'\n  \n  - http://195.133.27.184/list/\n  ?                         ^^\n  + http://195.133.27.184/login/\n  ?                        ++ ^", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a463866318c8c315df34d39a1cc63392\")>\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"a463866318c8c315df34d39a1cc63392\")>\n\n    @allure.title('Incorrect password-user not found')\n    @allure.description('Positive test--MMS element is displayed')\n    def test_incorrect_password(driver, wait):\n        login_page = LoginPage(driver)\n        login_page.sign_in(USERNAME, incorrect_password)\n>       assert driver.current_url == main_page_link, 'User not found'\nE       AssertionError: User not found\nE       assert 'http://195.133.27.184/login/' == 'http://195.133.27.184/list/'\nE         \nE         - http://195.133.27.184/list/\nE         ?                         ^^\nE         + http://195.133.27.184/login/\nE         ?                        ++ ^\n\ntests_tutors_web\\test_login_page.py:41: AssertionError"}, "description": "Positive test--MMS element is displayed", "start": 1731791436755, "stop": 1731791440829, "uuid": "0eb4cf25-ec9e-4cd5-a3b1-d4e943d7c0cb", "historyId": "6ecf56fc9733bf3be6d6c2acb947364f", "testCaseId": "6ecf56fc9733bf3be6d6c2acb947364f", "fullName": "tests_tutors_web.test_login_page#test_incorrect_password", "labels": [{"name": "parentSuite", "value": "tests_tutors_web"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "K-A-87-TY"}, {"name": "thread", "value": "1060-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests_tutors_web.test_login_page"}]}